import {locales} from "./appConstants";

export const content = Object.freeze({
    [locales.EN_US]: {
        SUBMIT: 'Submit',
        DOWNLOAD: 'Download',
        SELECT_FILE: 'Select file',
        PROCESSING: 'Please wait.......',
        TRIPLET_LIST_AND_STATS: 'Triplets list and other statistics',
        TRIPLET_LIST: 'Triplets list',
        FUNCTIONAL_SIZE: 'Functional size:',
        NUMBER_OF_INPUT_OPS: 'Number of input operations:',
        NUMBER_OF_OUTPUT_OPS: 'Number of output operations:',
        NUMBER_OF_READ_OPS: 'Number of read operations:',
        NUMBER_OF_WRITE_OPS: 'Number of write operations:',
        USE_FORM: 'Use form',
        USE_WORD_DOCUMENT: 'Use word document',
        USE_CASE_IS_IN_FR: 'Use case is in French',
        USE_CASE_IS_IN_EN: 'Use case is in English',
        SOMETHING_WENT_WRONG: 'Something went wrong, make sure the backend server is up and running!',
        TRIPLET: 'Triplet',
        OPERATION_TYPE: 'Operation Type',
        INCLUDE: 'Include',
        IN: 'Input',
        OUT: 'Output',
        WRITE: 'Write',
        READ: 'Read',
        UNKNOWN: 'Unknown',
    },
    [locales.FR]: {
        SUBMIT: 'Soumettre',
        DOWNLOAD: 'Telecharger',
        SELECT_FILE: 'Veuillez selectionner un fichier',
        PROCESSING: 'Traitement en cours.......',
        TRIPLET_LIST_AND_STATS: 'Liste des triplets generée et autres statistiques',
        TRIPLET_LIST: 'Liste des Triplets',
        FUNCTIONAL_SIZE: 'Taille fonctionnelle:',
        NUMBER_OF_INPUT_OPS: "Nombre d'operation d'entree:",
        NUMBER_OF_OUTPUT_OPS: "Nombre d'operation de sortie:",
        NUMBER_OF_READ_OPS: "Nombre d'operation de lecture:",
        NUMBER_OF_WRITE_OPS: "Nombre d'operation d'ecriture:",
        USE_FORM: 'Utiliser une forme',
        USE_WORD_DOCUMENT: 'Utiliser un document word',
        USE_CASE_IS_IN_FR: "Cas d'utilisation est en Français",
        USE_CASE_IS_IN_EN: "Cas d'utilisation est en Englais",
        SOMETHING_WENT_WRONG: "Une erreur s'est produite, veuillez verifier que le serveur est en marche!",
        TRIPLET: 'Triplet',
        OPERATION_TYPE: "Type d'operation",
        INCLUDE: 'Inclure',
        IN: 'Entrée',
        OUT: 'Sortie',
        WRITE: 'Ecriture',
        READ: 'Lecture',
        UNKNOWN: 'Inconnue',

    }
});
